### ISSUE TITLE
magnet links don't parse into anchor links in messages

### ISSUE THREAD

**Issue by du5t** [ssbc/ssb-markdown#11]
likely `mailto:` will fail for similar reasons

to reproduce: 
1. wrap a valid magnet link as you would an http url
2. submit a message thru, say, patchwork

**Comment by gmarcos87** [comment]
The magic happend in this line https://github.com/ssbc/ssb-markdown/blob/ba6255f6185a7855334719e13683bcaef6c6ec3e/index.js#L22

Maybe we can determine a list of protocols (which can be modified via opts) and iterate over that list.
In this issue (https://github.com/ssbc/patchwork/issues/616) request that url dat:// be links.
I imagine something like this:

```javascript
var protocols = this.protocols || ['http','dat','mailto','magnet']
function isLink (protocols, url) {
  var prot = decodeURIComponent(unescape(url.replace(/[^\w:]/g, ''))).toLowerCase()
  return protocols
            .filter(function (protocol) { return url.indexOf(protocol) === 0; })
            .reduce(function (prev,act) { return false; }, null)
}
```
