### ISSUE TITLE
does this have injection attacks?

### ISSUE THREAD

**Issue by dominictarr** [ssbc/ssb-markdown#16]
I look at the code and I'm not sure that this doesn't have attacks. given that this creates html on your computer from data distributed across a p2p network, if someone can create arbitary html (like script tags) by just posting code in a markdown link that would be a big security problem.

we need tests for this.

**Comment by kpcyrd** [comment]
I skipped through the source and I would recommend to do one of the following:

- use [virtual-dom] to build a tree safely and then return it, the code using this library would then `document.appendChild` it to the document (this is the easiest way)
- make ssb-markdown return a tree data structure and create a different library that does all the `document.createElement/document.appendChild` work for you. (the later library would require a browser, but ssb-markdown wouldn't)
- make ssb-markdown require a browser and call `document.createElement` inside this library.

All of these are breaking changes on how to use this library, but would prevent xss issues very reliable.

[virtual-dom]: https://github.com/Matt-Esch/virtual-dom

**Comment by clehner** [comment]
i was looking into ssb-marked recently and thinking of doing somthing like this. it could use the html-element module that hyperscript uses (or just use hyperscript) to make it work in browsers or on servers (where e.g. the dom tree gets converted to html before serving it to clients). i think the change would consist of a lot of changing some string concatenation to array pushing. this would also make it possible for the library to be more flexible in how it renders markdown to html elements. of course to just prevent xss it could probably be done by processing the html into virtual dom elements like you suggest the first way

**Comment by mitar** [comment]
I think a better approach is not to try to put too much logic into a markdown parser, but just use one which works, and then use a sanitizer at the end of the HTML output, which parses HTML, cleans it with a whitelist list of allowed tags and attributes, and renders it back to HTML. With this you remove all discrepancies between various browser HTML rendering engines.

The only thing you have then to worry about is that your markdown parser does not have some side effects during parsing (like executing JS, or making requests to resolve stuff).
