### ISSUE TITLE
# channel matching is including white space

### ISSUE THREAD

**Issue by mmckegg** [ssbc/ssb-markdown#19]
In the message `%a5hjte9+fx1rR90yUGhJAsadv0c1TeVyZ+/kehgJCF0=.sha256` the author wrote "Type a # character in the search bar in the upper right to show the list of channels" and `# character` turned into a hyperlink. 

The white space after the `#` should cause this to be ignored, but it is not.  

cc @clehner

**Comment by clehner** [comment]
Fixed in ssb-marked v0.7.2

**Comment by mmckegg** [comment]
Oh, here's something else: %xWfe/XBd0FqPMEfm8XQwAo0Ojz4UdojV3bshHcru5Co=.sha256

The punctuation '!' is being included in the channel name. Do we really want this?

**Comment by clehner** [comment]
> The punctuation '!' is being included in the channel name. Do we really want this?

probably not. maybe we should use a more sophisticated regex

**Comment by christianbundy** [comment]
Would this be resolved by using the [hashtag regex](https://github.com/mathiasbynens/hashtag-regex)? It's not pretty, but it's standardized rather than being arbitrary and SSB-specific. I'd be happy to merge it into my PR.
