### ISSUE TITLE
links inside code blocks?

### ISSUE THREAD

**Issue by jedahan** [ssbc/ssb-markdown#23]
I would love to render links inside code blocks, for example:

```
hello new friends

[my wobsite] is super kewl please visit!

[my wobsite]: https://hellonewfrien.ds
```

and have it output
```
hello new friends
my wobsite is super kewl please visit!
```
with [my wobsite](https://hellonewfrien.ds) being a link

**Comment by jedahan** [comment]
alternatively, having a monospaced rendered block would do the trick

**Comment by christianbundy** [comment]
Is this valid Markdown? If so, we can likely support it, but I don't think Markdown allows links in code blocks.

**Comment by christianbundy** [comment]
I don't think this would be a good fit for the Markdown renderer since it wouldn't be valid syntax. Maybe this would be a better fit for another renderer?
