### ISSUE TITLE
markdown-it isn't handling full dat urls correctly

### ISSUE THREAD

**Issue by mmckegg** [ssbc/ssb-markdown#25]
I just [added a failing test](https://github.com/ssbc/ssb-markdown/commit/5e45e2b1695d2f4b1fca42677349769001720e5b) that shows that full length dat:// urls aren't being linkified correctly when inserted as text.

Have traced this all the way to the dependency `mdurl`: https://github.com/markdown-it/mdurl/blob/master/parse.js#L83

It is enforcing that hostnames not be longer than 63 characters, but full dat hostnames are 64 😢 

```js
mdurl.parse('dat://fdc941b24e12cb84697e31304f27f4aeb4ff3b51e90bbf4c4853f5c0f5b047f0', true)
// => Url {
//  protocol: 'dat:',
//  slashes: true,
//  auth: null,
//  port: null,
//  hostname: 'fdc941b24e12cb84697e31304f27f4aeb4ff3b51e90bbf4c4853f5c0f5b047f',
//  hash: null,
//  search: null,
//  pathname: '0' }
```

(note that the `0` in `pathname` should actually be part of `hostname`)

cc @christianbundy

**Comment by christianbundy** [comment]
After consulting upstream it doesn't sound like we have any good options.

Dat identifiers don't follow the standards for URIs/URLs/etc., so we'd need to use [their parser](https://github.com/pfrazee/parse-dat-url) if we want to turn them all into links. We could use their parser and add a custom rule that checks for Dat identifiers, but that seems a bit clunky and gives the false impression that these identifiers can be read by other Markdown renderers too.

On one hand, I want to support what the Dat folks are working on and I'm tempted to add/maintain a chunk of code just to handle their identifier syntax. On the other hand, this doesn't seem very important to anyone working on Dat so I'm hesitant to bend over backward for interoperability when `<link>` is a standard that works everywhere.

@mmckegg What do you think we should do?
