### ISSUE TITLE
Make the markdown renderer include non-ascii characters in channel names

### ISSUE THREAD

**Issue by Powersource** [ssbc/ssb-markdown#34]
The title is maybe a bit unclear but my specific problem is that when you make a message saying "#malmö" it only renders "#malm" as clickable (and it takes you to the malm channel).

Everything else around this seems to work fine, I can go to the channel using the search box, subscribe to it, and the post linking "#malm"(ö) even ends up in the "#malmö" channel.

I have a feeling this is going to have to be fixed in a dep but I haven't had time to look into that yet.

**Comment by mmckegg** [comment]
A while back I also noticed that #art~hack would cause a similar issue (the tilde)

**Comment by qubist** [comment]
More info from an issue in the `markdown-it-hashtag` repo: https://github.com/svbergerem/markdown-it-hashtag/issues/2

**Comment by qubist** [comment]
PR #45 will close this issue

`#malmö`, hashtags with Chinese characters, accented characters like `#español`, etc. will work great! `#art~hack` won't work because from what I can tell, according to Unicode hashtag identifier syntax, the tilde `~` can't be in a hashtag.
