### ISSUE TITLE
images linked from the web being rendered!

### ISSUE THREAD

**Issue by mixmix** [ssbc/ssb-markdown#51]
Example : `%BzXb30J/zhMFg/EAVSpFiSBsSbb2S/BOLuidTA/E+pw=.sha256`
```
We are doing something in those lines with workshops in [HackBo](http://hackbo.co/), our local hackerspace. And while we present SSB to the participants, we also take some notes and create documentation in local language (Spanish). Below some links and screenshots about this:

I think that having a little bit of cash would help a lot, particularly in places like Hackerspaces, with run on a voluntary and donation post-capitalistic logic and not as business.

  * https://docutopia.tupale.co/s/dataroda38#
  * https://docutopia.tupale.co/s/ssb#

![](https://ia601400.us.archive.org/27/items/ssb_20200107/ssb.png)
```

---

**Renders in Patchbay :**

![image](https://user-images.githubusercontent.com/2665886/73118412-a56ae580-3fb8-11ea-83ab-5c1d19128d2d.png)

**Comment by mixmix** [comment]
This is very undesired behaviour - basically we wanted to prevent this happening in scuttlebutt because it leaks information about the location and reading-habits of users to the www.

this is the territory 1x1 pixel images with custom urls...

cc @christianbundy

**Comment by christianbundy** [comment]
Bad! I'm surprised we don't have a test for this. What should we change the `src` to if it's not a blob reference?

**Comment by christianbundy** [comment]
Oh, also: thanks for finding this and reporting it and pinging me. I went straight into problem-solving mode but I appreciate the time you spent figuring this out and making an issue (and CCing me!).

**Comment by staltz** [comment]
Hmm I think this might also happen in my markdown libraries for ssb (which are based on unifiedjs) for mobile
